# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

import torch.nn as nn
from hydra.utilities import get_free_space, move_batch_to_device
import numpy as np
from timeit import default_timer as timer

import torch
from hydra.components.partitioner.containers import ShardModel, ShardedTask
import traceback

from hydra.components.executor import Forward, ForwardLoss, Backward
import copy

import math

def tensor_partitioner(layer, batch, device):
    """
        Utility function to assist in generating tensor parallel shards.
        Takes as input a layer (assumed CNN for now), the intermediate/batch being passed in,
        and the relevant GPU.
        
        Note that each partition generated will be its own shard. Therefore we need not
        account for stacked graph costs throughout the shard (retain_graph), nor do
        we need to maintain an intermediate memory cost record.   
        
        
        Assumes (B, C, H, W, ...) input.
        
        Also assumes stride = 1 
            TODO: generalize beyond this assumption
    
        Currently assumes 2d input.
        
    """
    
    
    partition_count = 1
    successful_pass = False
    layer = layer.to(device)
    print("=======Tensor Parallel Partitioning=======")
    print("Initial batch size: {}".format(batch.shape))
    
    batch_dims = batch.shape[2:] # choose not to shard along batch dimension or channel dim
    chosen_dim = np.argmax(batch_dims)

    print("Known layer config details...")
    print("\t KERNEL SIZE: {}".format(layer.kernel_size))
    print("\t PADDING: {}".format(layer.padding))
    print("\t STRIDE: {}".format(layer.stride))
    
    
    # these formulas are 'padding=same' for both even and odd sized kernels
    # across the chosen dimension
    kernel_extension_prior = math.floor((layer.kernel_size[chosen_dim]-1) / 2)
    kernel_extension_latter = math.ceil((layer.kernel_size[chosen_dim]-1) / 2)
    
    print("PRIOR EXTENSION FOR SAME DIM OUTPUT: {}".format(kernel_extension_prior))
    print("LATTER EXTENSION FOR SAME DIM OUTPUT: {}".format(kernel_extension_latter))
    
    layer_padding = copy.deepcopy(layer.padding)
    layer.padding = 0
    flipped_dimension = len(layer_padding) - 1 - (chosen_dim)
    chosen_dim += 2 # offset for B, C dims
    
    
    
    while not successful_pass:
        print("Attempting {}-fold partitioning on dimensions: {}".format(partition_count, chosen_dim))
        try:
            
            
            all_outs = [] # all intermediates generated by the parallelized shards
            all_models = []
            forward_shards = []
            backward_shards = []
            padding_tuples = []
            
            remainder = batch.shape[chosen_dim] % partition_count
            previous_partition = 0
            partition_dimensional_value = 0
            time_taken_f = []
            time_taken_b = []
            partition_time = 0
            merger_time = 0
            
            for partition_index in range(partition_count):
                print("PREVIOUS PARTITION ENDED AT: {}".format(previous_partition))
                
                
                if (partition_index) < remainder:
                    partition_dimensional_value += math.floor(batch.shape[chosen_dim] / partition_count) + 1
                else:
                    partition_dimensional_value += math.floor(batch.shape[chosen_dim] / partition_count)

                
                
                """
                    Replace user-defined padding with a torch.nn.functional.pad that we can control.
                    
                    Internal-facing padding dimensions (i.e. pads that face the inside of the image) cannot be 
                    padded - that would affect correctness. Instead we apply an extension (overlap) with
                    other partitions and set padding in that direction to 0.

                """
                
                # NOTE: 
                # Strange PyTorch standard:
                # Input: N, C, H, W
                # Pad: Wr, Wl, Ht, Hb
                
                # Basically padding values.
                
                
                partition = None
                pad_layer = None
                
                

                # left-most/top-most/forward-most side of image
                if partition_index == 0:
                    padding_values = []
                    for pad_val in layer_padding:
                        padding_values.append(pad_val)
                        padding_values.append(pad_val)
                    padding_values[ flipped_dimension * 2 + 1] = 0
                    
                    
                    print("GENERATING PAD WITH SHAPE: {}".format(padding_values))
                    pad_layer = torch.nn.ZeroPad2d(padding_values) 
                    # replace this with torch.nn.functional pad to enable non-zero pad
                    
                    start = timer()
                    
                    print("SLICING FROM {} to {}".format(previous_partition, partition_dimensional_value+kernel_extension_latter))
                    slice_array = [slice(None) for x in range(len(batch.shape))]
                    slice_array[chosen_dim] = slice(None, partition_dimensional_value+kernel_extension_latter)
                    slice_array = tuple(slice_array)
                    print(slice_array)
                    partition = batch[slice_array]
                    
                    previous_partition = partition_dimensional_value
                    
                    partition_time += timer() - start
                    
                # right-most/bottom-most/back-most side of image
                elif partition_index == partition_count - 1:
                    padding_values = []
                    for pad_val in layer_padding:
                        padding_values.append(pad_val)
                        padding_values.append(pad_val)
                    padding_values[ flipped_dimension * 2] = 0
                    
                    print("GENERATING PAD WITH SHAPE: {}".format(padding_values))
                    pad_layer = torch.nn.ZeroPad2d(padding_values) # replace this with torch.nn.functional pad
                    
                    start = timer()
                    
                    print("SLICING FROM {} to {}".format(previous_partition-kernel_extension_prior, partition_dimensional_value))
                    slice_array = [slice(None) for x in range(len(batch.shape))]
                    slice_array[chosen_dim] = slice(previous_partition-kernel_extension_prior, None)
                    slice_array = tuple(slice_array)
                    #print(slice_array)
                    partition = batch[slice_array]
                    
                    previous_partition = partition_dimensional_value
                    
                    partition_time += timer() - start
                  
                # innards of image
                else:
                    padding_values = []
                    for pad_val in layer_padding:
                        padding_values.append(pad_val)
                        padding_values.append(pad_val)
                    padding_values[ flipped_dimension * 2] = 0
                    padding_values[ flipped_dimension * 2 + 1] = 0
                    
                    print("GENERATING PAD WITH SHAPE: {}".format(padding_values))
                    pad_layer = torch.nn.ZeroPad2d(padding_values) # replace this with torch.nn.functional pad
                    
                    start = timer()
                    
                    print("SLICING FROM {} to {}".format(previous_partition-kernel_extension_prior, partition_dimensional_value+kernel_extension_latter))
                    
                    
                    slice_array = [slice(None) for x in range(len(batch.shape))]
                    slice_array[chosen_dim] = slice(previous_partition-kernel_extension_prior, partition_dimensional_value+kernel_extension_latter)
                    slice_array = tuple(slice_array)
                    
                    partition = batch[slice_array]

                    previous_partition = partition_dimensional_value
                    
                    partition_time += timer() - start
              
                start = timer()
                print("PARTITION SHAPE: {}".format(partition.shape))
                partition = move_batch_to_device(partition, device)
        
                if (isinstance(partition, tuple) or isinstance(partition, list)):
                    out = pad_layer(*partition)
                    print("PAD OUTPUT SHAPE: {}".format(out.shape))
                    out = layer(out)
                    print("LAYER OUTPUT SHAPE: {}".format(out.shape))
                else:
                    out = pad_layer(partition)
                    print("PAD OUTPUT SHAPE: {}".format(out.shape))
                    out = layer(out)
                    print("LAYER OUTPUT SHAPE: {}".format(out.shape))
                    
                
                time_taken_f.append(timer() - start)
                start = timer()            
                grads = []
                new_out = []
                if not (isinstance(out, torch.Tensor)):
                    for output in out:
                        if output.requires_grad:
                            grads.append(torch.ones_like(output).to(device))
                            new_out.append(output)

                else:
                    if (out.requires_grad):
                        new_out.append(out)
                        grads.append(torch.ones_like(out).to(device))

                # Run a backward pass, each partition is required to be its own shard, so do not retain graph
                if (len(new_out)!= 0):
                    torch.autograd.backward(new_out, grads, retain_graph = False)
                    layer.zero_grad()

                del new_out
                del grads # Gradients are discarded immediately after use
                
                time_taken_b.append(timer() - start)
                
                               
                # GPU Memory Consumption is complete
                # if we reach this point we can safely assume the pass is safe. 
                # We can now update the input to prepare for the next layer.

                if not (isinstance(out, torch.Tensor)):
                    out = [x.cpu().detach().clone() for x in out]
                else:
                    out = out.cpu().detach().clone()
                    
                model = ShardModel(nn.ModuleList([pad_layer, layer]))
                all_models.append(model)
                all_outs.append(out)
            
            ##### SUCCESS! #####
            start = timer()
            
            cut_points = []
            current_index = 0
            for out in all_outs:
                current_index += out.shape[chosen_dim]
                cut_points.append(current_index)
            
            out = torch.cat(all_outs, chosen_dim)
            merger_time = timer()-start
            
            return partition_count, chosen_dim, all_models, out, time_taken_f, time_taken_b, partition_time, merger_time, cut_points 
            
            
        except Exception as e:
            print(e)
            partition_count += 1
            if (partition_count == 12):
                raise e
        
    
