# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

import torch.nn as nn
from hydra.utilities import get_free_space, move_batch_to_device
import numpy as np
from timeit import default_timer as timer

import torch
from hydra.components.partitioner.containers import ShardModel, ShardedTask
import traceback

from hydra.components.executor import Forward, ForwardLoss, Backward

import math

def tensor_partitioner(layer, batch, device):
    """
        Utility function to assist in generating tensor parallel shards.
        Takes as input a layer (assumed CNN for now), the intermediate/batch being passed in,
        and the relevant GPU.
        
        Note that each partition generated will be its own shard. Therefore we need not
        account for stacked graph costs throughout the shard (retain_graph), nor do
        we need to maintain an intermediate memory cost record.   
    
    """
    
    
    partition_count = 1
    successful_pass = False
    layer = layer.to(device)
    print("=======Tensor Parallel Partitioning=======")
    print("Initial batch size: {}".format(batch.shape))
    
    batch_dims = batch.shape[1:] # can't shard along batch dimension 
    chosen_dim = np.argmax(batch_dims)+1
    """
    try:
        print("INITIAL TESTS")
        batch = move_batch_to_device(batch, torch.device("cpu"))
        print(batch.get_device())
        torch.cuda.empty_cache()
        print("No batch memory consumption: {}".format(get_free_space(device.index)))
        batch = move_batch_to_device(batch, device)
        print(batch.get_device())
        print("Memory consumption with full batch: {}".format(get_free_space(device.index)))
        batch = move_batch_to_device(batch, torch.device("cpu"))
        torch.cuda.empty_cache()
        print("No batch (x2) memory consumption: {}".format(get_free_space(device.index)))
        partitioned_batches = torch.chunk(batch, 4, chosen_dim)
        partitions = []
        for partition in partitioned_batches:
            partitions.append(move_batch_to_device(partition, device))
        print("Memory consumption with partial batch: {}".format(get_free_space(device.index)))
        for index in range(len(partitions)):
            partitions[index] = move_batch_to_device(partition, torch.device("cpu"))
        torch.cuda.empty_cache()
        print("Memory consumption with partial batch CPU'd: {}".format(get_free_space(device.index)))
        raise RuntimeError("Error: shard size is 0")

    except Exception as e:
        print(e)
        raise e
    
    """
    
    
    
    
    while not successful_pass:
        print("Attempting {}-fold partitioning".format(partition_count))
        try:
            
            # BE CAREFUL - Split generates views, not new tensors. Evaluate memory costs to be sure that
            # only part of the batch is being moved.
            
            
            
            
            partitioned_batches = torch.chunk(batch, partition_count, chosen_dim)
            print("Partitioned {}X shape: {}".format(partition_count, partitioned_batches[0].shape))
            
            all_outs = [] # all intermediates generated by the parallelized shards
            for partition_index in range(partition_count):
                
                partition = move_batch_to_device(partitioned_batches[partition_index], device)
                
                if (isinstance(partition, tuple) or isinstance(partition, list)):
                    out = layer(*partition)
                else:
                    out = layer(partition)
                                 
                grads = []
                new_out = []
                if not (isinstance(out, torch.Tensor)):
                    for output in out:
                        if output.requires_grad:
                            grads.append(torch.ones_like(output).to(device))
                            new_out.append(output)

                else:
                    if (out.requires_grad):
                        new_out.append(out)
                        grads.append(torch.ones_like(out).to(device))

                # Run a backward pass, each partition is required to be its own shard, so do not retain graph
                if (len(new_out)!= 0):
                    torch.autograd.backward(new_out, grads, retain_graph = False)
                    layer.zero_grad()

                del new_out
                del grads # Gradients are discarded immediately after use
                
                               
                # GPU Memory Consumption is complete
                # if we reach this point we can safely assume the pass is safe. 
                # We can now update the input to prepare for the next layer.

                if not (isinstance(out, torch.Tensor)):
                    out = [x.cpu().detach().clone() for x in out]
                else:
                    out = out.cpu().detach().clone()
                    
                all_outs.append(out)
                
        except Exception as e:
            print(e)
            partition_count += 1
        
    
